### ISSUE TITLE
iOS _this2.setSrare is not a function

### ISSUE THREAD

**Issue by sparrowjack** [marcshilling/react-native-image-picker#77]
I am working on a project with react-native 0.17.
The majority part of image picker code is according to iOS Example/index.iOS.js file, which invoke selectPhotoTapped() method like this
```html
    <TouchableOpacity onPress={::this.selectPhotoTapped}>
    <View style={[styles.avatar, styles.avatarContainer, {marginBottom: 20}]}>
    { this.state.avatarSource === null ? <Text>Select a Photo</Text> :
    <Image style={styles.avatar} source={this.state.avatarSource} />
    }
    </View>
    </TouchableOpacity>
```
It worked well with react-native 0.12,but in 0.17, it told me that '{::this.selectPhotoTapped}'  was 'unexpected token'.And I modified to '{this.selectPhotoTapped}'. 
But after picking up image from the library,I can't get response.ui,either can I get the image path.

I am new to react-native,if there had something wrong,I will appreciate for your help!

**Comment by yfuks** [comment]
There is a breaking point with 0.12.0 image-picker

before
```javascript
UIImagePickerManager.showImagePicker(options, (didcancel, response) => {
```

now 
```javascript
UIImagePickerManager.showImagePicker(options, (response) => {
```

**Comment by sparrowjack** [comment]
![img_0505](https://cloud.githubusercontent.com/assets/7234299/12216730/46c50b60-b726-11e5-864f-78efddae2b6c.PNG)
I just found that the error screen has change like above

**Comment by yfuks** [comment]
replace

```javascript
<TouchableOpacity onPress={this.selectPhotoTapped}>
```
with
```javascript
<TouchableOpacity onPress={() => this.selectPhotoTapped()}>
```

to bind react class environement into your function

**Comment by sparrowjack** [comment]
Thanks for your patient.
