### ISSUE TITLE
cannot compile this project: "cannot find symbol import com.facebook.react.bridge.BaseActivityEventListener"

### ISSUE THREAD

**Issue by npomfret** [marcshilling/react-native-image-picker#386]
If i run:

```
./gradlew clean build
```

I get:

```
/Users/nickpomfret/Documents/github/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerActivityEventListener.java:6: error: cannot find symbol
import com.facebook.react.bridge.BaseActivityEventListener;
                                ^
  symbol:   class BaseActivityEventListener
  location: package com.facebook.react.bridge
```

Anyone know what's going on?

**Comment by marcshilling** [comment]
Try [this](https://github.com/marcshilling/react-native-image-picker/issues/324#issuecomment-248671904). Make sure to clean and rebuild after.

**Comment by npomfret** [comment]
Tried that, no luck. Are you able to get this project to compile in isolation - meaning without an enclosing react-native project (just on its own in android studio or the command line)?

The class in question (BaseActivityEventListener.class) doesn't seem to be in the react-native-0.21 jar file that the build brings in.  I've downloaded it and unzipped it to check, its not there.  I don't really understand how anyone get this to compile.  I also don't really understand why the latest version of react-native in maven central and jcentre is so old.  

I have a fix anyway, I'll send a PR through - although I don't really understand why its necessary.  Am I the only one who can't compile it?

**Comment by npomfret** [comment]
https://github.com/marcshilling/react-native-image-picker/pull/387

**Comment by marcshilling** [comment]
Yes, you are the only one who can't compile it. You're right, `BaseActivityEventListener` isn't in RN 21 -- why are you using that version? You're 15 versions behind...

**Comment by npomfret** [comment]
Look at [jcenter](https://bintray.com/bintray/jcenter/com.facebook.react%3Areact-native) or [maven](http://mvnrepository.com/artifact/com.facebook.react/react-native) - the last version to be uploaded is 0.20.1 back in feb

**Comment by npomfret** [comment]
Besides, the version of my app doesn't come into play here.  I checked out this project and ran `./gradlew clean build` and it doesn't compile.  If it doesn't compile for me how on earth does it compile for anyone else.

Have you tried first cleaning the your system?  I wonder if you've got some version of react-native in your local gradle cache that has that class file in.  Try clearing them out `rm -rf ~/.gradle/caches/*`?

**Comment by marcshilling** [comment]
That's your issue, RN doesn't use jcenter or maven anymore. The latest version is [0.37.0](https://github.com/facebook/react-native/releases/tag/v0.37.0).

You need to be installing react native (and this module) through npm. You have an odd project configuration and no one else is experiencing the issue.

**Comment by marcshilling** [comment]
Looking back to one of your posts: "Are you able to get this project to compile in isolation - meaning without an enclosing react-native project". No, of course not. This module is 100% reliant on React Native.

**Comment by npomfret** [comment]
Yes its reliant on react native, of course, but that's what the entry in [build.gradle](https://github.com/marcshilling/react-native-image-picker/blob/master/android/build.gradle#L43) is supposed to be for:

```
dependencies {
    compile "com.facebook.react:react-native:0.20.1"  // From node_modules
}
```

You should be able to at least compile a plugin without having to first include it in another app. No?  If not you might as well remove this dependency - it doesn't do anything.

**Comment by marcshilling** [comment]
>You should be able to at least compile a plugin without having to first include it in another app.

No...find me another React Native module that does this.

**Comment by marcshilling** [comment]
What do you mean the dependency doesn't do anything!?!?!! It's telling you that this project is dependent on React Native, which it very much is. You are either greatly confused about how React Native works, or I'm missing your actual issue here...

**Comment by npomfret** [comment]
Ok, so if this project doesn't compile on its own then it doesn't need a dependency on a very old version of react-native.  Which is what you've got.  Without this dependency (which gets ignored by your app at build-time because you app will pick its react native dependencies up from the node_modules directory), you app will build as normal.

Plenty of other react-native native models compile just fine in isolation.  Check out react-native-contacts, react-native-fs, react-native-blur, react-native-document-picker, react-native-couchbase-lite...

**Comment by marcshilling** [comment]
Dude, you're killing me. You posted a link to [build.gradle](https://github.com/marcshilling/react-native-image-picker/blob/master/android/build.gradle#L43), and then you posted an incorrect excerpt from it. The code is: 
```
dependencies {
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

Ok...so let's look at some of your awesome examples:

- [react-native-contacts](https://github.com/rt2zz/react-native-contacts/blob/master/android/build.gradle#L33) (this one actually links to version 0.12...)
- [react-native-fs](https://github.com/johanneslumpe/react-native-fs/blob/master/android/build.gradle#L29)
- [react-native-blur](https://github.com/react-native-community/react-native-blur/blob/master/android/build.gradle#L37)

Should I go on?

**Comment by marcshilling** [comment]
I think we're done here.

**Comment by npomfret** [comment]
Aaaargh, the point is THEY ALL COMPILE! And they compile on their own, without an enclosing project.  They have a build that works, why is that so controversial?

**Comment by varungupta85** [comment]
hi @marcshilling @npomfret , there has been a lot of discussion on this issue and I thought I will share my two cents because I ran into a similar thing with a different project to which I was adding some features and wanted to build it outside of my react-native application to cut down on the time before I find compilation errors and such. I am not an expert in react-native and I think you guys have a far better understanding of the inner workings of react-native than me.

I think the reason that the app compiles fine and these independent modules don't compile out of the box even though for both, the build.gradle states the dependency on `react-native` as `compile "com.facebook.react:react-native:+"  // From node_modules` is what is present in the `build.gradle` in the `android` directory. If you notice, in your react-native application, you have two build.gradle files, one in `android/app` directory which is the build.gradle for your app and one in `android` directory which contains some configuration which gets applied to all the projects. In that build.gradle, we specify the android specific react-native stuff to get from the local copy of react-native `url "$rootDir/../node_modules/react-native/android"`, so it doesn't even go to maven to get the published copy of react-native. I think if you were to copy over the contents of this build.gradle, mainly

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.google.gms:google-services:3.0.0' // Needed for Firebase Analytics
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

to this modules build.gradle, make sure that the url points to valid relative location (this could reference the react-native module in your app or a forked copy of react-native etc., run gradlew clean and build the project again, it should build. I haven't tried it with this project but have tried it with others and they build fine after I do the above. I think the reason, other RN modules that you mentioned compiles without any problem is that they are not implementing the `ActivityEventListener` interface which has changed over time more importantly since react-native 0.21 due to which you don't see the compilation errors in those projects that you see here.
