### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ajagesser** [marcshilling/react-native-image-picker#307]
I'm getting the following errors installing from IP 22.0 and up.
RN 0.31 and up gives the error

`/Users/Documents/workspace/mobile-app/node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java:58: error: ImagePickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class ImagePickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/Documents/workspace/mobile-app/node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java:290: error: method does not override or implement a method from a supertype
  @Override
  ^
2 errors
:react-native-image-picker:compileReleaseJavaWithJavac FAILED`

**Comment by devbriguy** [comment]
I have the same issue. +1.

**Comment by devbriguy** [comment]
I use BuddyBuild as my CI and it fails with these 2 errors. I'm using ```"react-native-image-picker": "^0.22.0"``` and react-native 0.29

**Comment by marcshilling** [comment]
Can you guys try version `0.22.3` on npm?

**Comment by marcshilling** [comment]
This is related to [this](https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35) commit, which landed in React Native 0.33. I'm looking into it.

**Comment by devbriguy** [comment]
Just to confirm 22.3 did not work.

**Comment by marcshilling** [comment]
So, for now I'm going to rollback the changes I made to support React Native 0.33. This seems like a gross oversight by the React Native team, but as far as I can tell, supporting the new `onActivityResult`

**Comment by marcshilling** [comment]
Should be back up and running again in `v0.22.4` on npm. However, remember this will only work on RN <= 0.32. I've created #308 to track this going forward.

**Comment by liuliangsir2016** [comment]
I have the same issue. +1.

**Comment by 748890753yiyi** [comment]
I have the same issue. +1,
I'm using "react-native-image-picker": "^0.26.3" and react-native 0.47.0
