### ISSUE TITLE
[Android] v0.22.5 doesn't compile with RN 0.33

### ISSUE THREAD

**Issue by hirviid** [marcshilling/react-native-image-picker#311]
Compilation fails (both dev and release) for version 0.22.5, with `error: cannot find symbol
import com.facebook.react.bridge.BaseActivityEventListener`:

```console
/Users/david/...../node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerActivityEventListener.java:6: error: cannot find symbol
import com.facebook.react.bridge.BaseActivityEventListener;
                                ^
  symbol:   class BaseActivityEventListener
  location: package com.facebook.react.bridge
/Users/david/...../node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerActivityEventListener.java:10: error: cannot find symbol
public class ImagePickerActivityEventListener extends BaseActivityEventListener {
                                                      ^
  symbol: class BaseActivityEventListener
/Users/david/...../node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerActivityEventListener.java:15: error: incompatible types: ImagePickerActivityEventListener cannot be converted to ActivityEventListener
        reactContext.addActivityEventListener(this);
```

**Comment by marcshilling** [comment]
Hard to believe...I was just working on this yesterday. Don't forget to npm install and run a gradle sync again.

**Comment by hirviid** [comment]
Your example works indeed, will try to find why it fails in my project and let you know.

**Comment by marcshilling** [comment]
A few things to check:
- In the project `build.gradle`, make sure the allProjects declaration looks like this:
```

**Comment by marcshilling** [comment]
A few things to check:

- In the project build.gradle, make sure the allProjects declaration looks like this:
```

**Comment by marcshilling** [comment]
A few things to check:

- In the project build.gradle, make sure the allprojects declaration looks like this:
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
- In the app `build.gradle`, ensure react-native is compiled like this: 
```
compile "com.facebook.react:react-native:+"  // From node_modules
```

And for good measure, run `./gradlew clean` inside the `android/` directory.

**Comment by hirviid** [comment]
Thanks @marcshilling !
Indeed, I had a build.gradle from an older react-native version, with `url "$projectDir/../../node_modules/react-native/android"`.

I changed it and now it works perfectly.

Thank you for your quick response.

**Comment by mcatmos** [comment]
Hi! I have the same problem, but I couldnt fixed, please @hirviid could you be more specific?

**Comment by hirviid** [comment]
Hi @mcatmos, I created a new project with `react-native init tempProject` and compared the android specific files with my project (initially created with RN 0.27.2). For me, changing `url` in android/build.gradle to `"$rootDir/../node_modules/react-native/android"` fixed it.

**Comment by agrass** [comment]
Hi! I changed to ``"$rootDir/../node_modules/react-native/android"`` but still the same problem. I'm with RN 0.26.2

**Comment by liuliangsir2016** [comment]
i met this issue a week ago,so sad

**Comment by marcshilling** [comment]
@liuliangsir2016 your code is incorrect. Your build.gradle url needs to be exactly `url "$rootDir/../node_modules/react-native/android"`. Then run clean and build.

**Comment by liuliangsir2016** [comment]
@marcshilling thx,it works

**Comment by booboothefool** [comment]
Today I learned you can't do this:

**android/build.gradle**
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
          url "$rootDir/../node_modules/react-native/android"
          url 'https://github.com/500px/500px-android-blur/raw/master/releases/'
        }
    }
}
```

gotta split up the maven stuff (I didn't even know what maven was)
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
          url "$rootDir/../node_modules/react-native/android"
        }
        maven {
          url 'https://github.com/500px/500px-android-blur/raw/master/releases/'
        }
  }
}
```
